### ISSUE TITLE
Label Images to JSON - Bad Edges

### ISSUE THREAD

**Issue by akeaveny** [hoangcuongbk80/python-tools#1]
Hi thanks for sharing your scripts for MaskRCNN!

I'm having issues converting this [dataset's](https://users.umiacs.umd.edu/~fer/affordance/part-affordance-dataset/index.html) _label.png to json using your [script ](https://github.com/hoangcuongbk80/python-tools/blob/master/labels_to_json_v2.py). I converted the gt mat files to _label.png.

The pixels are hand annotated and thus poor (see exaple below). The polygons for enclosing each object part are ok but the mask is not fully drawn. I noticed this happens for ~20% of the masks. 

I don't fully understand how to modify your code to improve my results.

![image](https://user-images.githubusercontent.com/56097508/83563609-5e05e000-a4e9-11ea-8ac5-ffc9fc052e6c.png)

![image](https://user-images.githubusercontent.com/56097508/83563637-6b22cf00-a4e9-11ea-99de-082db56d3979.png)

![image](https://user-images.githubusercontent.com/56097508/83563670-7413a080-a4e9-11ea-9535-92e19a5aa582.png)

**Comment by hoangcuongbk80** [comment]
Hi,

The algorithm is quite simple, given a mask image it find a edge point then find the closest edge point, the process last until reach the first point again. You can change variable "visual" to "True" to see the process. 

I do not see your problem from the pics above.

**Comment by akeaveny** [comment]
I included a GIF to help me explain. I realize I wasn't clear in my last post.

I hope it's easy to see that the handle isn't always properly drawn. This doesn't happen for all the models in the dataset but I can't understand why this happens for a select few.

The mask seems ok.


![Screencast-from-06-04-2020-05_45_43-PM](https://user-images.githubusercontent.com/56097508/83813490-7281de00-a68b-11ea-88a5-0f8e4964e2e1.gif)

**Comment by hoangcuongbk80** [comment]
Maybe its due to the mask is too thin. It might get wrong closest points. Let comment:
`#  edge_img = edge_downsample(edge_img)` 
and see can it helps.

**Comment by akeaveny** [comment]
Cheers! That helps, I'll close this issue. 
I appreciate you sharing your work, It has definetly helped me.

**Comment by hoangcuongbk80** [comment]
Good to hear that!

Actually the script is written for [this project](https://github.com/hoangcuongbk80/Object-RPE). So can you move your question and the solution to the project by creating a new issue there?. I think it can help others if they're facing the problem like yours. 

Thanks!
